/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.3.41"

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    jcenter()
    mavenCentral()
    maven {
        // confluent
        url = uri("https://packages.confluent.io/maven/")
    }
}


val kafka = "2.2.1"

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    // Kafka deps
    compile("org.apache.kafka:kafka-clients:2.2.1")
    compile("org.apache.kafka:kafka-streams:2.2.1")

    // config
    compile("com.sksamuel.hoplite:hoplite-core:1.1.4")
    compile("com.sksamuel.hoplite:hoplite-yaml:1.1.4")
}

application {
    // Define the main class for the application
    mainClassName = "com.hello.kafka.start.AppKt"
}
